# Default values for superplane.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: ghcr.io/superplanehq
  name: superplane
  pullPolicy: IfNotPresent
  pullSecrets: []

workers:
  replicas: 1
  dbPoolSize: 5
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

api:
  replicas: 1
  dbPoolSize: 5
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

domain:
  name: ""
  configMapName: "base-domain"

authentication:
  secretName: authentication
  github:
    enabled: true
    clientId: ""
    clientSecret: ""

#
# Key used to encrypt sensitive values before storing them in the database.
#
encryption:
  secretName: encryption
  key: ""

#
# Secret used to sign JWT tokens
#
jwt:
  secretName: jwt
  secret: ""

#
# Ingress configuration
#
ingress:
  enabled: true

  #
  # Specify the name of the static IP address
  # Required when ingress.className=gce
  #
  staticIpName: ""

  #
  # Set the Ingress class:
  # - gce: when deploying chart on GKE
  # - traefik: when deploying on VM with k3s
  #
  className: "gce"

  #
  # SSL Configuration
  #
  ssl:
    enabled: true
    type: "google"

    #
    # Use a Google-managed certificate.
    # Requires the name of the Google managed certificate in GCP
    #
    google:
      certName: ""

    #
    # Use a ALB certificate.
    #
    alb:
      certName: ""

    #
    # Provide a custom certificate managed by yourself.
    # Requires the fullchain certificate and the private key used to generate it,
    # which will be stored in a Kubernetes secret for usage.
    #
    custom:
      secretName: "tls-secret"
      crt: ""
      key: ""

#
# Postgres configuration
#
database:
  secretName: "postgres"
  host: "postgres"
  port: 5432
  username: postgres
  password: postgres
  ssl: false
  local:
    enabled: true
    version: 14.15-alpine3.21
    maxConnections: "1000"
    sharedBuffers: 1024MB
    size: 4Gi

#
# RabbitMQ configuration
#
rabbitmq:
  secretName: "rabbitmq"
  host: "rabbitmq"
  port: 5672
  managementPort: 15672
  username: rabbitmq
  password: rabbitmq
  protocol: amqp
  local:
    enabled: true
    version: 3.13.7-management-alpine
    size: 2Gi