apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-api
{{- if eq .Values.ingress.className "gce" }}
  annotations:
    cloud.google.com/backend-config: '{"default": "ingress-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
{{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: superplane
    service: {{ .Chart.Name }}-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: superplane
      service: {{ .Chart.Name }}-api
  template:
    metadata:
      name: {{ .Chart.Name }}-api
      labels:
        app: superplane
        service: {{ .Chart.Name }}-api
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.domain.configMapName }}
            - secretRef:
                name: {{ .Values.database.secretName }}
            - secretRef:
                name: {{ .Values.rabbitmq.secretName }}
            - secretRef:
                name: {{ .Values.authentication.secretName }}
            - secretRef:
                name: {{ .Values.encryption.secretName }}
            - secretRef:
                name: {{ .Values.jwt.secretName }}
            - secretRef:
                name: {{ .Values.session.secretName }}
          env:
            - name: START_PUBLIC_API
              value: "yes"
            - name: START_INTERNAL_API
              value: "yes"
            - name: START_GRPC_GATEWAY
              value: "true"
            - name: PUBLIC_API_BASE_PATH
              value: "/api/v1"
            - name: SWAGGER_BASE_PATH
              value: "/app/api/swagger"
            - name: RBAC_MODEL_PATH
              value: /app/rbac/rbac_model.conf
            - name: RBAC_ORG_POLICY_PATH
              value: /app/rbac/rbac_org_policy.csv
            - name: RBAC_CANVAS_POLICY_PATH
              value: /app/rbac/rbac_canvas_policy.csv
            - name: APPLICATION_NAME
              value: superplane
            - name: DB_POOL_SIZE
              value: {{ .Values.api.dbPoolSize }}

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: [ALL]

          {{- with .Values.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
