apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-workers
  namespace: {{ .Release.Namespace }}
  labels:
    app: superplane
    service: {{ .Chart.Name }}-workers
spec:
  replicas: {{ .Values.workers.replicas }}
  selector:
    matchLabels:
      app: superplane
      service: {{ .Chart.Name }}-workers
  template:
    metadata:
      name: {{ .Chart.Name }}-workers
      labels:
        app: superplane
        service: {{ .Chart.Name }}-workers
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-workers
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.domain.configMapName }}
            - secretRef:
                name: {{ .Values.database.secretName }}
            - secretRef:
                name: {{ .Values.rabbitmq.secretName }}
            - secretRef:
                name: {{ .Values.authentication.secretName }}
            - secretRef:
                name: {{ .Values.encryption.secretName }}
            - secretRef:
                name: {{ .Values.jwt.secretName }}
          env:
            - name: START_PENDING_EVENTS_WORKER
              value: "yes"
            - name: START_PENDING_STAGE_EVENTS_WORKER
              value: "yes"
            - name: START_TIME_WINDOW_WORKER
              value: "yes"
            - name: START_STAGE_EVENT_APPROVED_CONSUMER
              value: "yes"
            - name: START_EXECUTIONS_POLLER
              value: "yes"
            - name: START_EXECUTION_RESOURCE_POLLER
              value: "yes"
            - name: START_PENDING_FIELD_SETS_WORKER
              value: "yes"
            - name: START_PENDING_EVENT_SOURCES_WORKER
              value: "yes"
            - name: RBAC_MODEL_PATH
              value: /app/rbac/rbac_model.conf
            - name: RBAC_ORG_POLICY_PATH
              value: /app/rbac/rbac_org_policy.csv
            - name: RBAC_CANVAS_POLICY_PATH
              value: /app/rbac/rbac_canvas_policy.csv
            - name: APPLICATION_NAME
              value: superplane
            - name: DB_POOL_SIZE
              value: {{ .Values.workers.dbPoolSize }}

          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: [ALL]

          {{- with .Values.workers.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
